### ISSUE TITLE
configure issue

### ISSUE THREAD

**Issue by livibetter** [msharov/gjid#2]
If following the instruction in README, I got

```
% ./configure
./configure: line 61: ucc not found: command not found
./configure: line 62: -E: command not found
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
```

It is fixed with ucc compiler, which I doesn't have. Nonetheless, I have no problems to build directly with `make` and the game runs properly.

And the binary is built at `/tmp/$USER/make/gjid/gjid`, that's kind of strange to me.

**Comment by msharov** [comment]
Fixed by commit 68af2b97478a5403e09d1b154ec7edfab33f0147.

I really have to figure out some way to synchronize these configure scripts between projects. Each project ends up with its own version, with various things broken that were fixed in some other project, and when I try to update one script with another, bugs like this happen.

As for the /tmp location for the builddir, that is intentional. Modern distributions make /tmp a ramdisk, a good place to store temporary files. This is particularly helpful if your home directory is on an SSD; then frequent builds during development do not count toward its write endurance. You can change builddir location with configure --builddir yourplace.
